### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by milancurcic** [modern-fortran/neural-fortran#1]
Start with gfortran and `-DSERIAL`, build OpenCoarrays later if at all possible.

**Comment by milancurcic** [comment]
Do you know the gfortran version there? We're using `co_sum` and `co_broadcast` here. Even without OpenCoarrays (`-fcoarray=single`), it needs a relatively recent gfortran

**Comment by milancurcic** [comment]
I started looking more in the CircleCI direction, Travis has just been such a pain for me to learn because their lock-in to relatively old Ubuntus and opaque docs. What would you suggest using for potentially bleeding-edge Fortran features (F2018)? Can Travis be a reasonable choice here?

**Comment by scivision** [comment]
Yes it can. You can get up to gfortran-8 with Travis. Just change the reference to `gfortran-6` to `gfortran-8`.
However, if you want to use certain libraries that depend on the pre-gcc-8 ABI, then you might consider either a Bionic docker image, or using Appveyor, which comes with Ubuntu 18.04 as noted in my `.appveyor.yml` for tsunami.

You don't necessarily need Circle-CI, most things can be done with Travis. Just whatever one's preference is. I'm very familiar with Travis and AppVeyor.

**Comment by scivision** [comment]
If you want to do something that's easier in Ubuntu 18.04 than 16.04, consider AppVeyor as Ubuntu 18.04 is built in with
```yml
image:
- Ubuntu1804
```

You can use Docker through Travis or AppVeyor of course.

**Comment by scivision** [comment]
At the current time, I think that Travis is the only CI that has free Linux, Mac and Windows. AppVeyor has free Linux and Windows. Circle CI is free Linux.

**Comment by scivision** [comment]
A substantial percent of the Travis YML I see is needlessly overcomplicated, maybe because it was done for older Travis versions. let me know what you're trying to do and I can tell you if anything beyond plain Travis or AppVeyor YML is needed.

**Comment by milancurcic** [comment]
OK, thanks, super helpful info! I'm fine with sticking to Linux. Do you have a favorite Travis + docker YML example?

**Comment by scivision** [comment]
I am slimming a Docker image down for public release. I don't have a specific other Fortran Docker Travis example in mind, but basically one approach is:

0. Create suitable Docker image on laptop with Dockerfile, prioritizing small image size
1. Upload image to DockerHub
2. Create .travis.yml that pulls that Docker image, starts a Docker container and sends commands to the container "git pull" etc.

I have not determined if that's the most canonical way to use Travis for arbitrary Docker images. The download time for large Docker images is one reason I didn't use this widely on Travis, instead using the Docker image on private persistent resources that don't need to re-download the Docker image each time.

**Comment by scivision** [comment]
https://github.com/scivision/docker-fortran
Is an example of loading Ubuntu 18.04 on Travis for Fortran with CMake

**Comment by scivision** [comment]
https://github.com/scivision/docker-fortran
This example is now working again, with a non-sudo Docker container building and running multi-image coarray Fortran example on Travis-CI

**Comment by milancurcic** [comment]
It works, thanks @scivision !
