### ISSUE TITLE
get_set_network_params.f90 does not print the output of a logical test 

### ISSUE THREAD

**Issue by jvo203** [modern-fortran/neural-fortran#112]
I missed it in the review, the last line of code
```
print '(a)', 'Original and cloned network outputs match:', all(ypred1 == ypred2)
```
produces an empty test result:
```
Original and cloned network outputs match:
```

Obviously the ```'(a)'``` format string does not contain an entry for the second argument (the ```T```/```F``` logical result).

**Comment by milancurcic** [comment]
Thanks @jvo203, good eye.
