### ISSUE TITLE
MNIST example via PNG

### ISSUE THREAD

**Issue by serfcity** [modern-fortran/neural-fortran#125]
Can you add example witch user can test MNIST numbers detecting via setting path to PNG 28x28 image and weights files?

**Comment by milancurcic** [comment]
Unless there's an easy-to-include (as a dependency) and easy-to-use (as in, one function call to read an image into an array), this is likely out of scope.

The easiest way to go from PNG to reading in Fortran is to read the PNG in Python and write the array to a text file or a NumPy file, then read using Fortran stdlib.
