### ISSUE TITLE
Is CoArray that optional ?

### ISSUE THREAD

**Issue by aminiussi** [modern-fortran/neural-fortran#127]
Hi

The coarray dependency is marked as optional, but it seems that, at least with gcc 12.2.0, that you cannot use error stop without it.

Is that intended ?

Thanks

**Comment by milancurcic** [comment]
Hi Alain, that doesn't sound right.

Regarding the `error stop` issue, what exactly happens? Can you post a snippet that reproduces the behavior?

Regarding the `-DSERIAL=1`, I can't reproduce that either. What OS is this, and can you post your output of running cmake?
