### ISSUE TITLE
Preserve network metadata in save() and load()

### ISSUE THREAD

**Issue by milancurcic** [modern-fortran/neural-fortran#13]
Following-up on #12 , `net % save()` should store network metadata that is necessary for reproducing the output when loading from file using `net % load()`. 

At this time, the metadata are the activation functions used in each layer (all except input layer).

For example, this could take the format:

```
<number-of-layers>
<number-of-cells-per-each-layer>
<layer-number> <activation-function>
<layer-number> <activation-function>
...
<weights>
<biases>
```

**Comment by ivan-pi** [comment]
Hello Milan,

I see two ways to implement this:
1) the `layer_type` must store an allocatable character array that stores the activation string, or 
2) a helper function checks for each layer whether the activatoin function procedure pointer is associated with one of the existing activation functions and returns the correct string.

The first solution seems to be the most straightforward one. I would be happy to contribute a pull request.

According to the format you propose above the set_activation function could be suitably generalized with an optional layer argument to set a different activation function for each layer.

Best,

Ivan

**Comment by milancurcic** [comment]
Hi Ivan,

That would be great, please do. I like your suggestion 1.

Thanks,
milan

**Comment by milancurcic** [comment]
Great work, thanks Ivan!
