### ISSUE TITLE
Implement RMSprop in example/quadratic.f90

### ISSUE THREAD

**Issue by milancurcic** [modern-fortran/neural-fortran#136]
Let's make the first implementation in the example program and then we'll have a better idea how we need to refactor the library to integrate it there.

[Reference](https://en.wikipedia.org/wiki/Stochastic_gradient_descent#RMSProp)

**Comment by Spnetic-5** [comment]
Hello @milancurcic, As you know RMSProp invloves retrieving the `weights` and `gradients` of the network's layers, in order to update the weights based on the gradients. I don't see implementation of these two in `network` code, so how are we planning the implemention exactly.

**Comment by milancurcic** [comment]
Done by #144
