### ISSUE TITLE
Error while building in latest main 

### ISSUE THREAD

**Issue by Spnetic-5** [modern-fortran/neural-fortran#147]
@milancurcic I'm facing this error while building the current version of code.

![image](https://github.com/modern-fortran/neural-fortran/assets/66636289/953fe90d-1235-40a9-a866-1a334b05585f)

**Comment by milancurcic** [comment]
I get this error sometimes when I use the Modern Fortran extension in VS Code. The way I solve it is to `rm src/nf/*mod` from the top-level directory of the project before re-building.
