### ISSUE TITLE
v0.13.0 release

### ISSUE THREAD

**Issue by milancurcic** [modern-fortran/neural-fortran#149]
@Spnetic-5, can you please make the v0.13.0 release.

* Under "Choose a tag" enter "v0.13.0" and select "Create new tag"
* Under release title, enter "neural-fortran-0.13.0"
* Click on "Generate Release Notes"
* Preview, check, and publish

**Comment by Spnetic-5** [comment]
@milancurcic I think I don't have permissions to make new releases

**Comment by milancurcic** [comment]
Sorry, let me review the permissions and get back to you shortly.

**Comment by milancurcic** [comment]
Can you give it a try now?

**Comment by Spnetic-5** [comment]
Thank you, I have done it successfully🚀️

**Comment by milancurcic** [comment]
Awesome, thanks!
