### ISSUE TITLE
feature suggestion: load keras models from hdf5 file

### ISSUE THREAD

**Issue by peterukk** [modern-fortran/neural-fortran#15]
just found this project, seems interesting!

I would venture to guess that there is more demand for doing neural network inference in Fortran, rather than both training and inference. This may be outside the scope for this project, but being able to load neural networks trained in Keras/TensorFlow (in Python) would be an extremely useful feature, akin to https://github.com/Dobiasd/frugally-deep . Maybe I'll have a look at it myself if I get the time, should be fairly simple for feedforward nets using the supported activations.

**Comment by milancurcic** [comment]
I'd say that'd be very much within the scope of the project. Ideally we'd make the linking with HDF5 optional. Take a look at what @jordanott has done in his fork https://github.com/jordanott/neural-fortran.

I have little experience with HDF5 myself, but would be happy to help in this effort.

**Comment by peterukk** [comment]
Thanks for the link; the python script by jornadott for converting keras model files to text files neural-fortran understands worked great after changing one line in [neural_fortran.py](https://github.com/jordanott/neural-fortran/blob/master/KerasWeightsProcessing/neural_fortran.py)

` activations.append(model_config['config']['layers'][num]['config']['activation']) `

to        

` activations.append(model_config['config'][num]['config']['activation']) `

Maybe due to a different version of keras. Anyway, I think it's a good solution for now. I implemented my models successfully with neural-fortran and the inference seems very fast!

**Comment by ashishmagar600** [comment]
@peterukk The link for file "neural_fortran.py" isn't working. The file has been removed from the repository. Can you share the file via an attachment here? 
There is another Python script [https://github.com/jordanott/neural-fortran/blob/master/KerasWeightsProcessing/convert_weights.py](url)  which says "Convert Keras Weights to Text File". Don't know if it converts the complete model or just the weights. Also, no **issues** page there.

**Comment by peterukk** [comment]
the file you want is still in the repository, but the file name was changed to convert_weights.py

```
import h5py
import json
import argparse
import numpy as np

def get_available_layers(layers, available_layers=[b"dense"]):
    parsed_layers = []
    for l in layers:
        for g in available_layers:
            if g in l:
                parsed_layers.append(l)
    return parsed_layers

def h5_to_txt(weights_file_name, output_file_name=''):

    #check and open file
    with h5py.File(weights_file_name,'r') as weights_file:

        weights_group_key=list(weights_file.keys())[0]

        # activation function information in model_config
        model_config = weights_file.attrs['model_config'].decode('utf-8') # Decode using the utf-8 encoding
        model_config = model_config.replace('true','True')
        model_config = model_config.replace('false','False')

        model_config = model_config.replace('null','None')
        model_config = eval(model_config)

        layers = list(weights_file['model_weights'].attrs['layer_names'])
        layers = get_available_layers(layers)
        print("names of layers in h5 file: %s \n" % layers)

        # attributes needed for .txt file
        # number of layers + 1(Fortran includes input layer),
        #   dimensions, biases, weights, and activations
        num_layers = len(layers)+1

        dimensions = []
        bias = {}
        weights = {}
        activations = []

        print('Processing the following {} layers: \n{}\n'.format(len(layers),layers))
        if 'Input' in model_config['config']['layers'][0]['class_name']:
            model_config = model_config['config']['layers'][1:]
        else:
            model_config = model_config['config']['layers']

        for num,l in enumerate(layers):
            layer_info_keys=list(weights_file[weights_group_key][l][l].keys())

            #layer_info_keys should have 'bias:0' and 'kernel:0'
            for key in layer_info_keys:
                if "bias" in key:
                    bias.update({num:np.array(weights_file[weights_group_key][l][l][key])})

                elif "kernel" in key:
                    weights.update({num:np.array(weights_file[weights_group_key][l][l][key])})
                    if num == 0:
                        dimensions.append(str(np.array(weights_file[weights_group_key][l][l][key]).shape[0]))
                        dimensions.append(str(np.array(weights_file[weights_group_key][l][l][key]).shape[1]))
                    else:
                        dimensions.append(str(np.array(weights_file[weights_group_key][l][l][key]).shape[1]))

            if 'Dense' in model_config[num]['class_name']:
                activations.append(model_config[num]['config']['activation'])
            else:
                print('Skipping bad layer: \'{}\'\n'.format(model_config[num]['class_name']))

    if not output_file_name:
        # if not specified will use path of weights_file with txt extension
        output_file_name = weights_file_name.replace('.h5', '.txt')

    with open(output_file_name,"w") as output_file:
        output_file.write(str(num_layers) + '\n')

        output_file.write("\t".join(dimensions) + '\n')
        if bias:
            for x in range(len(layers)):
                bias_str="\t".join(list(map(str,bias[x].tolist())))
                output_file.write(bias_str + '\n')
        if weights:
            for x in range(len(layers)):
                weights_str="\t".join(list(map(str,weights[x].T.flatten())))
                output_file.write(weights_str + '\n')
        if activations:
            for a in activations:
                if a == 'softmax':
                    print('WARNING: Softmax activation not allowed... Replacing with Linear activation')
                    a = 'linear'
                output_file.write(a + "\n")



kerasfile = "mykerasmodel.h5"
model.save(kerasfile)

newfile = kerasfile[:-3]+".txt"
print(newfile)

h5_to_txt(kerasfile,newfile)
```

**Comment by ashishmagar600** [comment]
Thanks a lot.

**Comment by xushanthu-2014** [comment]
Thanks sharing this package! Now I am also planning embed trained Keras ML model into a fortran90 script. Could you please generate small examples for how to propagating the loaded ml model in Fortran? for example, if I have load the ```my_model.txt``` in the fortran script by ```call net % load('model_config.txt')```, how can I calculate the forward output using some arbitrary inputs? thanks!

**Comment by milancurcic** [comment]
#79 is now merged. See the example on reading a simple Keras model from HDF5: [mnist_from_keras](https://github.com/modern-fortran/neural-fortran/blob/main/example/mnist_from_keras.f90).

I'll close this issue and let's open new issues specific to expanding the Keras reader functionality.
