### ISSUE TITLE
Can you explain what is "Fortran 2018-compatible compiler"? Where to download free compiler for Windows?

### ISSUE THREAD

**Issue by kething** [modern-fortran/neural-fortran#20]
Hi I wasn't able to run the example_mnist, probably I don't have the right Fortran 2018-compatible compiler. Could you explain where to get the Fortran 2018 compatible compiler?
Sorry I am new in learning and using Fortran, could you show me how to get started with the setup and run the example? 
Thank you.

**Comment by milancurcic** [comment]
Sorry for the late response, I missed the notification. 

As of a recent commit (https://github.com/modern-fortran/neural-fortran/commit/674fcfa1e10246ed88b8efd987f5badd9c6e6da3), Fortran 2018 stuff is used only if you need parallel execution. So a reasonably recent gfortran compiler will work. 

On Windows, your best bet is [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10). 

Some people use [Cygwin](https://www.cygwin.com/) successfully, though I haven't heard reports of neural-fortran builds there. I also don't see a reason why it shouldn't work. I don't have experience with it.

**Comment by kething** [comment]
Milan, thank you for the reply.
