### ISSUE TITLE
Predicting continuous outputs outside (0,1)

### ISSUE THREAD

**Issue by Beliavsky** [modern-fortran/neural-fortran#21]
In example_sine.f90 the response

y = (sin(x * 2 * pi) + 1) * 0.5

takes on values between 0 and 1. How would the code be modified to predict an unbounded continuous variable? Thanks for neural-fortran.

**Comment by milancurcic** [comment]
During training, both inputs x and outputs y must be scaled to the [0, 1] range. In this example, I intentionally used x in [0, 1], and y [-1, 1] scaled to [0, 1] for simplicity.

Once the network is trained and you're ready for prediction, you do the scaling again: scale input x to [0, 1]. The prediction will be in the [0, 1] range. Then you scale it back to its actual value. 

You do need to decide on some reasonable values for bounds, this could be the min/max values of your labels from the training set.

I bet there are common rules of thumb for these things in the literature, I just don't quite follow it so I'm not aware.
