### ISSUE TITLE
Type mismatch for array length arguments?

### ISSUE THREAD

**Issue by septcolor** [modern-fortran/neural-fortran#26]
In the constructor for `array1d` and `array2d`, the dummy arguments are declared as `integer`, but isn't it better to declare as `integer(ik)` ? (because `db_init()` and `dw_init()` passes `integer(ik)` as actual arguments)

```  
pure type(array1d) function array1d_constructor(length) result(a)
    ! Overloads the default type constructor.
    integer, intent(in) :: length
    allocate(a % array(length))
    a % array = 0
  end function array1d_constructor

  pure type(array2d) function array2d_constructor(dims) result(a)
    ! Overloads the default type constructor.
    integer, intent(in) :: dims(2)
    allocate(a % array(dims(1), dims(2)))
    a % array = 0
  end function array2d_constructor
```

Related lines:
https://github.com/modern-fortran/neural-fortran/blob/master/src/lib/mod_layer.f90#L63

https://github.com/modern-fortran/neural-fortran/blob/master/src/lib/mod_layer.f90#L70

https://github.com/modern-fortran/neural-fortran/blob/master/src/lib/mod_layer.f90#L83

https://github.com/modern-fortran/neural-fortran/blob/master/src/lib/mod_layer.f90#L96

**Comment by milancurcic** [comment]
You're right, I think it is. Mind submitting a PR? Thank you!
