### ISSUE TITLE
I have listed neural-fortran on a Machine Learning package list on GitHub

### ISSUE THREAD

**Issue by shahmoradi** [modern-fortran/neural-fortran#27]
Hi Milan, I have added `neural-fortran` to [this popular list of machine learning packages](https://github.com/josephmisiti/awesome-machine-learning/pull/722) on GitHub and have requested a pull. Hope you do not mind. To do so, I created a new section on Fortran and listed `neural-fortran` along with [ParaMonte](https://github.com/cdslaborg/paramonte) as the two Fortran machine learning packages that I know about, at the moment. Hopefully, this will lead to increased visibility of `neural-fortran` and the Fortran language in general.

**Comment by milancurcic** [comment]
Thank you, @shahmoradi!
