### ISSUE TITLE
Provide different back-ends?

### ISSUE THREAD

**Issue by ivan-pi** [modern-fortran/neural-fortran#28]
Would it be possible to use sub-modules to provide different backends to the neural-fortran interface?

What I have in mind are things like:
* [Intel® oneAPI Deep Neural Network Library](https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/onednn.html)
* [Tensorflow](https://www.tensorflow.org/api_docs)
* [Fann](http://leenissen.dk/fann/wp/) (a Fortran interface for this one already exists [here](http://leenissen.dk/fann/wp/language-bindings/))
* [Several other NN libraries](https://en.wikipedia.org/wiki/Comparison_of_deep-learning_software)

While I admire the effort to build a pure Fortran NN library, the amount of effort (and money) being put into these other libraries is simply enormous. Perhaps this way disciplines traditionally reliant upon Fortran (meteorology, quantum chemistry, ...) could also benefit from the numerous existing machine learning frameworks containing all kinds of advanced graph and runtime optimizations.

The way I see this working, is we need to define (and possibly expand) the high-level interface for creating and training NNs. Then the non-Fortran implementations (effectively just adaptors to other frameworks) can be placed in submodules which could be switched on by a CMake flag.

**Comment by ivan-pi** [comment]
Digging deeper into TensorFlow as an example, they have some documents on how to build bindings for other languages through the C api:
* [TensorFlow in other languages](https://github.com/tensorflow/docs/blob/master/site/en/r1/guide/extend/bindings.md)
* [C API](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h)

The C API however, is still in development, and doesn't support all the features of TensorFlow in Python. I've found a few blog posts on how the C API can be used to call an existing graph:
* [Deploying Tensorflow as C/C++ executable](https://github.com/AmirulOm/tensorflow_capi_sample)
* [Undocumented Tensorflow C API](https://medium.com/@vladislavsd/undocumented-tensorflow-c-api-b527c0b4ef6)

It looks more complicated than I expected.

**Comment by milancurcic** [comment]
Thank you for the proposal! It sounds like a useful though daunting effort. I won't be able to lead the development but I'd be happy to help. I'm also open to changes to the API.

All this assuming that any added back-end would be optional at build time.

**Comment by milancurcic** [comment]
I just became aware of [pytorch-fortran](https://github.com/alexeedm/pytorch-fortran).

**Comment by milancurcic** [comment]
There's also [Fortran Torch Adapter](https://github.com/luc99hen/FTA), which takes a similar approach to pytorch-fortran.

**Comment by milancurcic** [comment]
Thank you for the suggestion again. After some time, I'm more convinced that neural-fortran will remain a pure Fortran approach so alternative backends are out of scope.
