### ISSUE TITLE
How to use your package in other fortran90 project?

### ISSUE THREAD

**Issue by xushanthu-2014** [modern-fortran/neural-fortran#29]
Thanks for providing this nice package to implement keras/tensorflow in fortran!
Now I want to do some innovations to embed machine learning algorithms in one atmospheric model which is written by fortran 90. And this model use ```make``` to compile ```Makefile```. And I put this ```Makefile``` in a google document here: https://docs.google.com/document/d/10naj1WgE9P4qbILT3n85TosZCd1KISwSzGw2u5FIOwo/edit. So how can I use your ```FKB``` or ```neural-fortran``` in my project? I suppose I should put the library file ```.o``` in my library? or put the ```.mod``` in my ```.mod``` directory of the atmospheric model? And after that, what should I do? how can I embed your ```Cmakelist.txt``` into my ```Makefile```?
by the way, could you please write a ```readme``` to illustrate how to use your project into my own fortran projects? Thanks!

**Comment by milancurcic** [comment]
Hi @xushanthu-2014, it looks like you got good suggestions on Discourse. Best to continue in that thread, and I'll close this one. Let me know if you need more help.

**Comment by xushanthu-2014** [comment]
Hi @milancurcic, thanks for your reply! Somebody on Discourse suggested me to use FPM. But I don't know how to use FPM to add external library to existing programs...could you please help with that? Thanks! I also add a discussion under the FPM: https://github.com/fortran-lang/fpm/discussions/494

**Comment by milancurcic** [comment]
Neural-fortran is not an fpm package yet, though I've been meaning to do it, just haven't made it a priority. This issue motivates me. But fpm would be useful only if your complex atmospheric model was also an fpm package. Then you could just add neural-fortran as a dependency. But as it is, I think the best approach for you is to link to neural-fortran from within the build system of your atmospheric model.

**Comment by xushanthu-2014** [comment]
Hi @milancurcic, thanks for your reply! That model is a land surface model (SURFEX) from France. Maybe it's not in your FPM package...it's here: http://www.umr-cnrm.fr/surfex/spip.php?article191. This version is a public version. So maybe you could also add it into fpm? But one thing is that, in the installation and building process, it requires ```./configure```. So what else do I need to do beyond just "adding one line like ```gfortran using_fkb.f90 -I/path_to_fkb/libneural.o```"? Thanks a lot!
