### ISSUE TITLE
Use the directory structure to more obviously expose the user API

### ISSUE THREAD

**Issue by rouson** [modern-fortran/neural-fortran#72]
@milancurcic I keep feeling silly when I realize things that probably should have been obvious.  It was very helpful that your [comment] on PR #71 pointed me to the nf module for the user API.   I recommend using a directory structure first suggested to me by @everythingfunctional and which I've subsequently adopted on all libraries that I develop.   For neural-fortran, the directory tree would look like the one below.  I'll submit a new PR that organizes

```
% tree src 
src
├── nf
│   ├── nf_activation.f90
│   ├── nf_base_layer.f90
│   ├── nf_base_layer_submodule.f90
│   ├── nf_conv2d_layer.f90
│   ├── nf_conv2d_layer_submodule.f90
│   ├── nf_datasets_mnist.f90
│   ├── nf_datasets_mnist_submodule.f90
│   ├── nf_dense_layer.f90
│   ├── nf_dense_layer_submodule.f90
│   ├── nf_input1d_layer.f90
│   ├── nf_input1d_layer_submodule.f90
│   ├── nf_input3d_layer.f90
│   ├── nf_input3d_layer_submodule.f90
│   ├── nf_io.f90
│   ├── nf_io_submodule.f90
│   ├── nf_layer.f90
│   ├── nf_layer_constructors.f90
│   ├── nf_layer_constructors_submodule.f90
│   ├── nf_layer_submodule.f90
│   ├── nf_loss.f90
│   ├── nf_loss_submodule.f90
│   ├── nf_maxpool2d_layer.f90
│   ├── nf_maxpool2d_layer_submodule.f90
│   ├── nf_network.f90
│   ├── nf_network_submodule.f90
│   ├── nf_optimizers.f90
│   ├── nf_parallel.f90
│   ├── nf_parallel_submodule.f90
│   ├── nf_random.f90
│   └── nf_random_submodule.f90
└── nf.f90
```

[comment]: https://github.com/modern-fortran/neural-fortran/pull/71#issuecomment-1130196862

**Comment by milancurcic** [comment]
Thanks for the suggestion. I'm not in favor of this change at this time. This is putting almost all source files one level down, only to indicate which module should be used in applications. If it's not clear enough from the [examples](https://github.com/modern-fortran/neural-fortran#examples) then let's improve the (missing) user docs.

**Comment by milancurcic** [comment]
I changed my mind about this after our call. It's one way to help make the user API clearer to newcomers, so let's do it.
