### ISSUE TITLE
Protect the main branch

### ISSUE THREAD

**Issue by rouson** [modern-fortran/neural-fortran#73]
I just mistakenly committed to my local main branch and then pushed my commit to this repository's main branch.  To recover from this, I then reset my local main branch to the immediately prior commit and force-pushed to this repository's main branch.  I recommend protecting the main branch of the repository so that no one can push directly to the main branch.  I don't think I have sufficient privileges to protect the main branch myself.   

I'll submit a pull request to merge a new branch into main to make the changes that I was trying to suggest when I mistakenly pushed to main.

**Comment by milancurcic** [comment]
OK, thanks, I just did that.
