### ISSUE TITLE
more stock examples 

### ISSUE THREAD

**Issue by andrewczgithub** [modern-fortran/neural-fortran#8]
Hi @milancurcic !

Really liking the style of the book.
I was wondering if you are going to include more examples with stock data.
Maybe a neural network forecast and backtest?

Many thanks,
Best,
Andrew

**Comment by milancurcic** [comment]
Hi Andrew,

I'm happy that you're enjoying the book. 

It's a good idea for a stock price prediction example and the toy dataset from https://github.com/modern-fortran/stock-prices would be small and easy enough to include, even as a regression test. From the top of my head, I am not quite sure what kind of network structure would be appropriate for this problem and would need some research.

Do you have any ideas or links to existing tutorials that address these kinds of problems (time series prediction)?
