### ISSUE TITLE
Memory leak in get_keras_h5_layers

### ISSUE THREAD

**Issue by jacobwilliams** [modern-fortran/neural-fortran#82]
In `get_keras_h5_layers`, this code:

```fortran
    call json % parse(model_config_json, model_config_string)
```

allocates the local `model_config_json` pointer, but it is not destroyed in this routine, so that's a memory leak. You should add a:

```fortran
   call json % destroy (model_config_json)
```

At the end to free the memory. The other `json_value` pointers all look like they are just pointing to data inside this structure, so you don't have to worry about those.

FYI: the higher-level `json_file` class is a little safer (but less flexible) to use since it will destroy the pointer when it goes out of scope (it has a finalizer). What you have here is fine though (you just need the `destroy` call at the end).

**Comment by milancurcic** [comment]
Thanks! Mind putting a quick PR for this? I would like to add you to the list of contributors.
